if(EXISTS "/home/agaton14/Documents/JiNP/lab2/zbiory/unit_tests[1]_tests.cmake")
  include("/home/agaton14/Documents/JiNP/lab2/zbiory/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
