if(EXISTS "/home/agaton14/Dokumenty/Programowanie-w-cpp/lab4 - wyrazenia regularne/unit_tests[1]_tests.cmake")
  include("/home/agaton14/Dokumenty/Programowanie-w-cpp/lab4 - wyrazenia regularne/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
